import "Windows.ApplicationModel.Core.idl";

namespace Cpp
{
    runtimeclass FrameworkView;

    runtimeclass FrameworkViewSource;

}

namespace Cpp
{
    [version(1.0)]
    [activatable(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    runtimeclass FrameworkViewSource
    {
        [default]
        interface Windows.ApplicationModel.Core.IFrameworkViewSource;        
    };

    [version(1.0)]
    [activatable(1.0)]
    [marshaling_behavior(agile)]
    [threading(both)]
    runtimeclass FrameworkView
    {
        [default]
        interface Windows.ApplicationModel.Core.IFrameworkView;
    };
}